name: Build TcpKiller

on:
  push:
    branches: [ master ]
    
jobs:
  build:
#     strategy:
#       matrix:
#         os: [ubuntu-18.04, macos-10.15, windows-2019]
#     runs-on: ${{ matrix.os }}
    runs-on: windows-2019
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 8.0.222
        java-package: jdk+fx
        
    - name: Install InnoSetp
      if: runner.os == 'Windows'
      run: choco install innosetup --version=5.5.9
      
    - name: Run Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: jfxNative


