name: Build TcpKiller

on:
  push:
    branches: [ master ]
    
jobs:
  build:
#     strategy:
#       matrix:
#         os: [ubuntu-18.04, macos-10.15, windows-2019]
#     runs-on: ${{ matrix.os }}
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 8.0.222
        java-package: jdk+fx
    
    - name: Uninstall InnoSetup 6
      if: runner.os == 'Windows'
      run: choco uninstall innosetup
    
    - name: Install InnoSetup 5
      if: runner.os == 'Windows'
      run: choco install innosetup --version=5.5.9 --force --allow-empty-checksums
      
    - name: Print iscc help  
      if: runner.os == 'Windows'
      run: C:\ProgramData\Chocolatey\bin\iscc.exe /?
      
    - name: Install Wixtoolset
      if: runner.os == 'Windows'
      run: choco install wixtoolset
      
    - name: Run Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: jfxNative

    - run: dir build\jfx\native

