name: Build TcpKiller

on:
  push:
    branches: [ master ]
    
jobs:
  build:
#     strategy:
#       matrix:
#         os: [ubuntu-18.04, macos-10.15, windows-2019]
#     runs-on: ${{ matrix.os }}
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '9.0.4'
        java-package: jdk+fx
    
    - name: Uninstall InnoSetup 6
      if: runner.os == 'Windows'
      run: choco uninstall innosetup
    
    - name: Install InnoSetup 5
      if: runner.os == 'Windows'
      run: choco install innosetup --version=5.5.9 --force --allow-empty-checksums
 
    - name: ls innosetup
      if: runner.os == 'Windows'
      run: pwd
    
    - name: Add to path
      if: runner.os == 'Windows'
      run: echo "##[add-path]C:\Program Files (x86)\Inno Setup 5\bin"
     
    - run: $Env:Path
#     - name: Print iscc help  
#       if: runner.os == 'Windows'
#       run: C:\Program Files (x86)\Inno Setup 5\bin\iscc.exe /?
      
#     - name: Install Wixtoolset
#       if: runner.os == 'Windows'
#       run: choco install wixtoolset
#     - name: List available
#       uses: eskatos/gradle-command-action@v1
#       with:
#        arguments: jfxListBundlers
         
    - name: Run Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: jfxNative
        
    - run: ls build
    - run: ls build\jfx
    - run: ls build\jfx\app
    - run: ls build\jfx\native
    - run: ls build\jfx\native\TcpKiller
